<?php

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Etrias\RaseConnector\SoapTypes;

class AxdEntity_MarkupTransLine
{
    /**
     * @var AxdExtType_AmountCur
     */
    protected $CalculatedAmount = null;

    /**
     * @var string
     */
    protected $ChargeIndicatorEinvoice = null;

    /**
     * @var AxdUnion_AxdExtType_CurrencyCode_AxdType_ExtCodeValue
     */
    protected $CurrencyCode = null;

    /**
     * @var AxdEnum_DocumentStatus
     */
    protected $DocumentStatus = null;

    /**
     * @var AxdExtType_InterCompanyInvoiceId
     */
    protected $InterCompanyInvoiceId = null;

    /**
     * @var AxdExtType_InterCompanyMarkupUseValue
     */
    protected $InterCompanyMarkupUseValue = null;

    /**
     * @var AxdExtType_InterCompanyMarkupValue
     */
    protected $InterCompanyMarkupValue = null;

    /**
     * @var AxdExtType_RefRecId
     */
    protected $InterCompanyRefRecId = null;

    /**
     * @var AxdExtType_MarkupKeep
     */
    protected $Keep = null;

    /**
     * @var AxdExtType_LineNum
     */
    protected $LineNum = null;

    /**
     * @var AxdExtType_MarkupCategoryType
     */
    protected $MarkupCategory = null;

    /**
     * @var AxdUnion_AxdExtType_MarkupCode_AxdType_ExtCodeValue
     */
    protected $MarkupCode = null;

    /**
     * @var AxdExtType_MarkupModuleCategory
     */
    protected $ModuleCategory = null;

    /**
     * @var AxdExtType_MarkupModule
     */
    protected $ModuleType = null;

    /**
     * @var AxdExtType_recId
     */
    protected $OrigRecId = null;

    /**
     * @var AxdExtType_tableId
     */
    protected $OrigTableId = null;

    /**
     * @var AxdExtType_AmountCur
     */
    protected $Posted = null;

    /**
     * @var AxdExtType_recId
     */
    protected $RecId = null;

    /**
     * @var AxdExtType_recVersion
     */
    protected $RecVersion = null;

    /**
     * @var AxdExtType_TaxAmountCur
     */
    protected $TaxAmount = null;

    /**
     * @var AxdExtType_TaxAutoGenerated
     */
    protected $TaxAutogenerated = null;

    /**
     * @var AxdExtType_TaxGroup
     */
    protected $TaxGroup = null;

    /**
     * @var AxdExtType_TaxItemGroup
     */
    protected $TaxItemGroup = null;

    /**
     * @var AxdExtType_TaxWriteCode
     */
    protected $TaxWriteCode = null;

    /**
     * @var AxdExtType_TransDate
     */
    protected $TransDate = null;

    /**
     * @var AxdExtType_recId
     */
    protected $TransRecId = null;

    /**
     * @var AxdExtType_tableId
     */
    protected $TransTableId = null;

    /**
     * @var AxdExtType_TransTxt
     */
    protected $Txt = null;

    /**
     * @var AxdExtType_MarkupValue
     */
    protected $Value = null;

    /**
     * @var AxdExtType_Voucher
     */
    protected $Voucher = null;

    /**
     * @var UNKNOWN
     */
    protected $class = null;

    /**
     * @var AxdEnum_AxdEntityAction
     */
    protected $action = null;

    /**
     * Constructor.
     *
     * @var AxdExtType_AmountCur
     * @var string                                                $ChargeIndicatorEinvoice
     * @var AxdUnion_AxdExtType_CurrencyCode_AxdType_ExtCodeValue $CurrencyCode
     * @var AxdEnum_DocumentStatus                                $DocumentStatus
     * @var AxdExtType_InterCompanyInvoiceId                      $InterCompanyInvoiceId
     * @var AxdExtType_InterCompanyMarkupUseValue                 $InterCompanyMarkupUseValue
     * @var AxdExtType_InterCompanyMarkupValue                    $InterCompanyMarkupValue
     * @var AxdExtType_RefRecId                                   $InterCompanyRefRecId
     * @var AxdExtType_MarkupKeep                                 $Keep
     * @var AxdExtType_LineNum                                    $LineNum
     * @var AxdExtType_MarkupCategoryType                         $MarkupCategory
     * @var AxdUnion_AxdExtType_MarkupCode_AxdType_ExtCodeValue   $MarkupCode
     * @var AxdExtType_MarkupModuleCategory                       $ModuleCategory
     * @var AxdExtType_MarkupModule                               $ModuleType
     * @var AxdExtType_recId                                      $OrigRecId
     * @var AxdExtType_tableId                                    $OrigTableId
     * @var AxdExtType_AmountCur                                  $Posted
     * @var AxdExtType_recId                                      $RecId
     * @var AxdExtType_recVersion                                 $RecVersion
     * @var AxdExtType_TaxAmountCur                               $TaxAmount
     * @var AxdExtType_TaxAutoGenerated                           $TaxAutogenerated
     * @var AxdExtType_TaxGroup                                   $TaxGroup
     * @var AxdExtType_TaxItemGroup                               $TaxItemGroup
     * @var AxdExtType_TaxWriteCode                               $TaxWriteCode
     * @var AxdExtType_TransDate                                  $TransDate
     * @var AxdExtType_recId                                      $TransRecId
     * @var AxdExtType_tableId                                    $TransTableId
     * @var AxdExtType_TransTxt                                   $Txt
     * @var AxdExtType_MarkupValue                                $Value
     * @var AxdExtType_Voucher                                    $Voucher
     * @var UNKNOWN                                               $class
     * @var AxdEnum_AxdEntityAction                               $action
     *
     * @param mixed $CalculatedAmount
     * @param mixed $ChargeIndicatorEinvoice
     * @param mixed $CurrencyCode
     * @param mixed $DocumentStatus
     * @param mixed $InterCompanyInvoiceId
     * @param mixed $InterCompanyMarkupUseValue
     * @param mixed $InterCompanyMarkupValue
     * @param mixed $InterCompanyRefRecId
     * @param mixed $Keep
     * @param mixed $LineNum
     * @param mixed $MarkupCategory
     * @param mixed $MarkupCode
     * @param mixed $ModuleCategory
     * @param mixed $ModuleType
     * @param mixed $OrigRecId
     * @param mixed $OrigTableId
     * @param mixed $Posted
     * @param mixed $RecId
     * @param mixed $RecVersion
     * @param mixed $TaxAmount
     * @param mixed $TaxAutogenerated
     * @param mixed $TaxGroup
     * @param mixed $TaxItemGroup
     * @param mixed $TaxWriteCode
     * @param mixed $TransDate
     * @param mixed $TransRecId
     * @param mixed $TransTableId
     * @param mixed $Txt
     * @param mixed $Value
     * @param mixed $Voucher
     * @param mixed $class
     * @param mixed $action
     */
    public function __construct($CalculatedAmount, $ChargeIndicatorEinvoice, $CurrencyCode, $DocumentStatus, $InterCompanyInvoiceId, $InterCompanyMarkupUseValue, $InterCompanyMarkupValue, $InterCompanyRefRecId, $Keep, $LineNum, $MarkupCategory, $MarkupCode, $ModuleCategory, $ModuleType, $OrigRecId, $OrigTableId, $Posted, $RecId, $RecVersion, $TaxAmount, $TaxAutogenerated, $TaxGroup, $TaxItemGroup, $TaxWriteCode, $TransDate, $TransRecId, $TransTableId, $Txt, $Value, $Voucher, $class, $action)
    {
        $this->CalculatedAmount = $CalculatedAmount;
        $this->ChargeIndicatorEinvoice = $ChargeIndicatorEinvoice;
        $this->CurrencyCode = $CurrencyCode;
        $this->DocumentStatus = $DocumentStatus;
        $this->InterCompanyInvoiceId = $InterCompanyInvoiceId;
        $this->InterCompanyMarkupUseValue = $InterCompanyMarkupUseValue;
        $this->InterCompanyMarkupValue = $InterCompanyMarkupValue;
        $this->InterCompanyRefRecId = $InterCompanyRefRecId;
        $this->Keep = $Keep;
        $this->LineNum = $LineNum;
        $this->MarkupCategory = $MarkupCategory;
        $this->MarkupCode = $MarkupCode;
        $this->ModuleCategory = $ModuleCategory;
        $this->ModuleType = $ModuleType;
        $this->OrigRecId = $OrigRecId;
        $this->OrigTableId = $OrigTableId;
        $this->Posted = $Posted;
        $this->RecId = $RecId;
        $this->RecVersion = $RecVersion;
        $this->TaxAmount = $TaxAmount;
        $this->TaxAutogenerated = $TaxAutogenerated;
        $this->TaxGroup = $TaxGroup;
        $this->TaxItemGroup = $TaxItemGroup;
        $this->TaxWriteCode = $TaxWriteCode;
        $this->TransDate = $TransDate;
        $this->TransRecId = $TransRecId;
        $this->TransTableId = $TransTableId;
        $this->Txt = $Txt;
        $this->Value = $Value;
        $this->Voucher = $Voucher;
        $this->class = $class;
        $this->action = $action;
    }

    /**
     * @return AxdExtType_AmountCur
     */
    public function getCalculatedAmount()
    {
        return $this->CalculatedAmount;
    }

    /**
     * @param AxdExtType_AmountCur $CalculatedAmount
     *
     * @return $this
     */
    public function setCalculatedAmount($CalculatedAmount)
    {
        $this->CalculatedAmount = $CalculatedAmount;

        return $this;
    }

    /**
     * @return string
     */
    public function getChargeIndicatorEinvoice()
    {
        return $this->ChargeIndicatorEinvoice;
    }

    /**
     * @param string $ChargeIndicatorEinvoice
     *
     * @return $this
     */
    public function setChargeIndicatorEinvoice($ChargeIndicatorEinvoice)
    {
        $this->ChargeIndicatorEinvoice = $ChargeIndicatorEinvoice;

        return $this;
    }

    /**
     * @return AxdUnion_AxdExtType_CurrencyCode_AxdType_ExtCodeValue
     */
    public function getCurrencyCode()
    {
        return $this->CurrencyCode;
    }

    /**
     * @param AxdUnion_AxdExtType_CurrencyCode_AxdType_ExtCodeValue $CurrencyCode
     *
     * @return $this
     */
    public function setCurrencyCode($CurrencyCode)
    {
        $this->CurrencyCode = $CurrencyCode;

        return $this;
    }

    /**
     * @return AxdEnum_DocumentStatus
     */
    public function getDocumentStatus()
    {
        return $this->DocumentStatus;
    }

    /**
     * @param AxdEnum_DocumentStatus $DocumentStatus
     *
     * @return $this
     */
    public function setDocumentStatus($DocumentStatus)
    {
        $this->DocumentStatus = $DocumentStatus;

        return $this;
    }

    /**
     * @return AxdExtType_InterCompanyInvoiceId
     */
    public function getInterCompanyInvoiceId()
    {
        return $this->InterCompanyInvoiceId;
    }

    /**
     * @param AxdExtType_InterCompanyInvoiceId $InterCompanyInvoiceId
     *
     * @return $this
     */
    public function setInterCompanyInvoiceId($InterCompanyInvoiceId)
    {
        $this->InterCompanyInvoiceId = $InterCompanyInvoiceId;

        return $this;
    }

    /**
     * @return AxdExtType_InterCompanyMarkupUseValue
     */
    public function getInterCompanyMarkupUseValue()
    {
        return $this->InterCompanyMarkupUseValue;
    }

    /**
     * @param AxdExtType_InterCompanyMarkupUseValue $InterCompanyMarkupUseValue
     *
     * @return $this
     */
    public function setInterCompanyMarkupUseValue($InterCompanyMarkupUseValue)
    {
        $this->InterCompanyMarkupUseValue = $InterCompanyMarkupUseValue;

        return $this;
    }

    /**
     * @return AxdExtType_InterCompanyMarkupValue
     */
    public function getInterCompanyMarkupValue()
    {
        return $this->InterCompanyMarkupValue;
    }

    /**
     * @param AxdExtType_InterCompanyMarkupValue $InterCompanyMarkupValue
     *
     * @return $this
     */
    public function setInterCompanyMarkupValue($InterCompanyMarkupValue)
    {
        $this->InterCompanyMarkupValue = $InterCompanyMarkupValue;

        return $this;
    }

    /**
     * @return AxdExtType_RefRecId
     */
    public function getInterCompanyRefRecId()
    {
        return $this->InterCompanyRefRecId;
    }

    /**
     * @param AxdExtType_RefRecId $InterCompanyRefRecId
     *
     * @return $this
     */
    public function setInterCompanyRefRecId($InterCompanyRefRecId)
    {
        $this->InterCompanyRefRecId = $InterCompanyRefRecId;

        return $this;
    }

    /**
     * @return AxdExtType_MarkupKeep
     */
    public function getKeep()
    {
        return $this->Keep;
    }

    /**
     * @param AxdExtType_MarkupKeep $Keep
     *
     * @return $this
     */
    public function setKeep($Keep)
    {
        $this->Keep = $Keep;

        return $this;
    }

    /**
     * @return AxdExtType_LineNum
     */
    public function getLineNum()
    {
        return $this->LineNum;
    }

    /**
     * @param AxdExtType_LineNum $LineNum
     *
     * @return $this
     */
    public function setLineNum($LineNum)
    {
        $this->LineNum = $LineNum;

        return $this;
    }

    /**
     * @return AxdExtType_MarkupCategoryType
     */
    public function getMarkupCategory()
    {
        return $this->MarkupCategory;
    }

    /**
     * @param AxdExtType_MarkupCategoryType $MarkupCategory
     *
     * @return $this
     */
    public function setMarkupCategory($MarkupCategory)
    {
        $this->MarkupCategory = $MarkupCategory;

        return $this;
    }

    /**
     * @return AxdUnion_AxdExtType_MarkupCode_AxdType_ExtCodeValue
     */
    public function getMarkupCode()
    {
        return $this->MarkupCode;
    }

    /**
     * @param AxdUnion_AxdExtType_MarkupCode_AxdType_ExtCodeValue $MarkupCode
     *
     * @return $this
     */
    public function setMarkupCode($MarkupCode)
    {
        $this->MarkupCode = $MarkupCode;

        return $this;
    }

    /**
     * @return AxdExtType_MarkupModuleCategory
     */
    public function getModuleCategory()
    {
        return $this->ModuleCategory;
    }

    /**
     * @param AxdExtType_MarkupModuleCategory $ModuleCategory
     *
     * @return $this
     */
    public function setModuleCategory($ModuleCategory)
    {
        $this->ModuleCategory = $ModuleCategory;

        return $this;
    }

    /**
     * @return AxdExtType_MarkupModule
     */
    public function getModuleType()
    {
        return $this->ModuleType;
    }

    /**
     * @param AxdExtType_MarkupModule $ModuleType
     *
     * @return $this
     */
    public function setModuleType($ModuleType)
    {
        $this->ModuleType = $ModuleType;

        return $this;
    }

    /**
     * @return AxdExtType_recId
     */
    public function getOrigRecId()
    {
        return $this->OrigRecId;
    }

    /**
     * @param AxdExtType_recId $OrigRecId
     *
     * @return $this
     */
    public function setOrigRecId($OrigRecId)
    {
        $this->OrigRecId = $OrigRecId;

        return $this;
    }

    /**
     * @return AxdExtType_tableId
     */
    public function getOrigTableId()
    {
        return $this->OrigTableId;
    }

    /**
     * @param AxdExtType_tableId $OrigTableId
     *
     * @return $this
     */
    public function setOrigTableId($OrigTableId)
    {
        $this->OrigTableId = $OrigTableId;

        return $this;
    }

    /**
     * @return AxdExtType_AmountCur
     */
    public function getPosted()
    {
        return $this->Posted;
    }

    /**
     * @param AxdExtType_AmountCur $Posted
     *
     * @return $this
     */
    public function setPosted($Posted)
    {
        $this->Posted = $Posted;

        return $this;
    }

    /**
     * @return AxdExtType_recId
     */
    public function getRecId()
    {
        return $this->RecId;
    }

    /**
     * @param AxdExtType_recId $RecId
     *
     * @return $this
     */
    public function setRecId($RecId)
    {
        $this->RecId = $RecId;

        return $this;
    }

    /**
     * @return AxdExtType_recVersion
     */
    public function getRecVersion()
    {
        return $this->RecVersion;
    }

    /**
     * @param AxdExtType_recVersion $RecVersion
     *
     * @return $this
     */
    public function setRecVersion($RecVersion)
    {
        $this->RecVersion = $RecVersion;

        return $this;
    }

    /**
     * @return AxdExtType_TaxAmountCur
     */
    public function getTaxAmount()
    {
        return $this->TaxAmount;
    }

    /**
     * @param AxdExtType_TaxAmountCur $TaxAmount
     *
     * @return $this
     */
    public function setTaxAmount($TaxAmount)
    {
        $this->TaxAmount = $TaxAmount;

        return $this;
    }

    /**
     * @return AxdExtType_TaxAutoGenerated
     */
    public function getTaxAutogenerated()
    {
        return $this->TaxAutogenerated;
    }

    /**
     * @param AxdExtType_TaxAutoGenerated $TaxAutogenerated
     *
     * @return $this
     */
    public function setTaxAutogenerated($TaxAutogenerated)
    {
        $this->TaxAutogenerated = $TaxAutogenerated;

        return $this;
    }

    /**
     * @return AxdExtType_TaxGroup
     */
    public function getTaxGroup()
    {
        return $this->TaxGroup;
    }

    /**
     * @param AxdExtType_TaxGroup $TaxGroup
     *
     * @return $this
     */
    public function setTaxGroup($TaxGroup)
    {
        $this->TaxGroup = $TaxGroup;

        return $this;
    }

    /**
     * @return AxdExtType_TaxItemGroup
     */
    public function getTaxItemGroup()
    {
        return $this->TaxItemGroup;
    }

    /**
     * @param AxdExtType_TaxItemGroup $TaxItemGroup
     *
     * @return $this
     */
    public function setTaxItemGroup($TaxItemGroup)
    {
        $this->TaxItemGroup = $TaxItemGroup;

        return $this;
    }

    /**
     * @return AxdExtType_TaxWriteCode
     */
    public function getTaxWriteCode()
    {
        return $this->TaxWriteCode;
    }

    /**
     * @param AxdExtType_TaxWriteCode $TaxWriteCode
     *
     * @return $this
     */
    public function setTaxWriteCode($TaxWriteCode)
    {
        $this->TaxWriteCode = $TaxWriteCode;

        return $this;
    }

    /**
     * @return AxdExtType_TransDate
     */
    public function getTransDate()
    {
        return $this->TransDate;
    }

    /**
     * @param AxdExtType_TransDate $TransDate
     *
     * @return $this
     */
    public function setTransDate($TransDate)
    {
        $this->TransDate = $TransDate;

        return $this;
    }

    /**
     * @return AxdExtType_recId
     */
    public function getTransRecId()
    {
        return $this->TransRecId;
    }

    /**
     * @param AxdExtType_recId $TransRecId
     *
     * @return $this
     */
    public function setTransRecId($TransRecId)
    {
        $this->TransRecId = $TransRecId;

        return $this;
    }

    /**
     * @return AxdExtType_tableId
     */
    public function getTransTableId()
    {
        return $this->TransTableId;
    }

    /**
     * @param AxdExtType_tableId $TransTableId
     *
     * @return $this
     */
    public function setTransTableId($TransTableId)
    {
        $this->TransTableId = $TransTableId;

        return $this;
    }

    /**
     * @return AxdExtType_TransTxt
     */
    public function getTxt()
    {
        return $this->Txt;
    }

    /**
     * @param AxdExtType_TransTxt $Txt
     *
     * @return $this
     */
    public function setTxt($Txt)
    {
        $this->Txt = $Txt;

        return $this;
    }

    /**
     * @return AxdExtType_MarkupValue
     */
    public function getValue()
    {
        return $this->Value;
    }

    /**
     * @param AxdExtType_MarkupValue $Value
     *
     * @return $this
     */
    public function setValue($Value)
    {
        $this->Value = $Value;

        return $this;
    }

    /**
     * @return AxdExtType_Voucher
     */
    public function getVoucher()
    {
        return $this->Voucher;
    }

    /**
     * @param AxdExtType_Voucher $Voucher
     *
     * @return $this
     */
    public function setVoucher($Voucher)
    {
        $this->Voucher = $Voucher;

        return $this;
    }

    /**
     * @return UNKNOWN
     */
    public function getClass()
    {
        return $this->class;
    }

    /**
     * @param UNKNOWN $class
     *
     * @return $this
     */
    public function setClass($class)
    {
        $this->class = $class;

        return $this;
    }

    /**
     * @return AxdEnum_AxdEntityAction
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * @param AxdEnum_AxdEntityAction $action
     *
     * @return $this
     */
    public function setAction($action)
    {
        $this->action = $action;

        return $this;
    }
}
